Eliminate imports from plata.product.stock within plata.payments.modules.
 -- otherwise order.payments.pending().delete() was causing:
      DatabaseError: relation "stock_stocktransaction" does not exist
      LINE 1: DELETE FROM "stock_stocktransaction" WHERE "stock_stocktr...